package com.dynonuggets.refonteimplicaction.job.jobposting.dto.enums;

public enum BusinessSectorEnum {
    AGROALIMENTAIRE, BANQUE, ASSURANCE, IMPRIMERIE, BTP, CHIMIE, COMMERCE, EDITION, COMMUNICATION, ELECTRONIQUE,
    ETUDES_ET_CONSEILS, INDUSTRIE_PHARMACEUTIQUE, INFORMATIQUE, TELECOMS, AUTOMOBILE, METALLURGIE, SERVICES_AUX_ENTREPRISES,
    TEXTILE, TRANSPORTS, LOGISTIQUE
}
