version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'implicaction'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - "9030:8080"
  aws:
    image: adobe/s3mock
    ports:
      - "9090:9090"
    expose:
      - "9090"

volumes:
  my-db:
