name: Workflow Maven

on:
  push:
    branches:
    - workflow*
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
    
  # deploy:
  #   defaults:
  #     run:
  #       shell: bash
  #       working-directory: frontend-implicaction
  #   name: Front workflow
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     - name: Login to Dockerhub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME}}
  #         password: ${{secrets.DOCKER_TOKEN}}
  #     - name: Build and push
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: frontend-implicaction
  #         push: true
  #         tags: ${{ secrets.DOCKER_USERNAME}}/dyno-nuggets:latest
